CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-avg --FL_algorithm FedAvg --dataset imagenet --data_root /home/bd/data/zs/FedMMDP/preprocessed_imagenet/domain_datasets --lr 1e-5 --local_epochs 1 --comm_rounds 20  --batch_size 256 --model clip --use_pretrained_proj 0 --partition hetero >outputs/output_avg_clip.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-prox --FL_algorithm FedProx --dataset imagenet --data_root /home/bd/data/zs/FedMMDP/preprocessed_imagenet/domain_datasets --lr 1e-5 --local_epochs 1 --comm_rounds 20 --model clip --batch_size 256 --use_pretrained_proj 0 --partition hetero >outputs/output_prox.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-md --FL_algorithm FedMD --dataset imagenet --data_root /home/bd/data/zs/FedMMDP/preprocessed_imagenet/domain_datasets --lr 1e-5 --local_epochs 1 --comm_rounds 20 --model clip --batch_size 256 --pub_data_num 5000 --use_pretrained_proj 0 --partition hetero >outputs/output_md.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-df --FL_algorithm FedDF --dataset imagenet --data_root /home/bd/data/zs/FedMMDP/preprocessed_imagenet/domain_datasets --lr 1e-5 --local_epochs 1 --comm_rounds 20 --model clip --batch_size 256 --pub_data_num 5000 --use_pretrained_proj 0 --partition hetero >outputs/output_df.log 2>&1 &

CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-Cream --FL_algorithm Cream --dataset imagenet --data_root /home/bd/data/zs/FedMMDP/preprocessed_imagenet/domain_datasets --lr 1e-5 --local_epochs 1 --comm_rounds 20 --model clip --batch_size 256 --pub_data_num 5000 --use_pretrained_proj 0 --partition hetero >outputs/output_cream.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-Harmony --FL_algorithm Harmony --dataset imagenet --data_root /home/bd/data/zs/FedMMDP/preprocessed_imagenet/domain_datasets --lr 1e-5 --local_epochs 1 --comm_rounds 20 --harmony_stage1_rounds 10 --harmony_clusters 2 --harmony_cluster_mode fixed --model clip --batch_size 256 --use_pretrained_proj 0 --partition hetero >outputs/output_Harmony.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-MASA --FL_algorithm MASA --dataset imagenet --data_root /home/bd/data/zs/FedMMDP/preprocessed_imagenet/domain_datasets --lr 1e-5 --local_epochs 1 --comm_rounds 20 --model clip --batch_size 256 --use_pretrained_proj 0 --partition hetero >outputs/output_MASA.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-MEMA --FL_algorithm FedMEMA --dataset imagenet --data_root /home/bd/data/zs/FedMMDP/preprocessed_imagenet/domain_datasets --lr 1e-5 --local_epochs 1 --comm_rounds 20 --model clip --batch_size 256 --use_pretrained_proj 0 --partition hetero >outputs/output_FedMEMA.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-Mobile --FL_algorithm FedMobile --dataset imagenet --data_root /home/bd/data/zs/FedMMDP/preprocessed_imagenet/domain_datasets --lr 1e-5 --local_epochs 1 --comm_rounds 20 --model clip --batch_size 256 --use_pretrained_proj 0 --partition hetero >outputs/output_FedMobile.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-MEKT --FL_algorithm FedMEKT --dataset imagenet --data_root /home/bd/data/zs/FedMMDP/preprocessed_imagenet/domain_datasets --lr 1e-5 --local_epochs 1 --comm_rounds 20 --model clip --batch_size 256 --use_pretrained_proj 0 --partition hetero >outputs/output_FedMEKT.log 2>&1 &

CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-MMDP --FL_algorithm FedMMDP --dataset imagenet --data_root /home/bd/data/zs/FedMMDP/preprocessed_imagenet/domain_datasets --lr 1e-5 --local_epochs 1 --comm_rounds 20 --model clip --batch_size 256 --use_pretrained_proj 1 --partition hetero >outputs/output_FedMMDP.log 2>&1 &
