export IMAGENET_SIGLIP_ROOT=/home/bd/data/zs/FedMMDP/preprocessed_imagenet/domain_datasets/siglip

CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-avg --FL_algorithm FedAvg --data_root "$IMAGENET_SIGLIP_ROOT" --feature_dim 768 --lr 1e-5 --local_epochs 1 --comm_rounds 20  --batch_size 256 --model clip --use_pretrained_proj 0 --partition hetero >outputs/output_avg_clip_siglip.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-prox --FL_algorithm FedProx --data_root "$IMAGENET_SIGLIP_ROOT" --feature_dim 768 --lr 1e-5 --local_epochs 1 --comm_rounds 20 --model clip --batch_size 256 --use_pretrained_proj 0 --partition hetero >outputs/output_prox_siglip.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-md --FL_algorithm FedMD --data_root "$IMAGENET_SIGLIP_ROOT" --feature_dim 768 --lr 1e-5 --local_epochs 1 --comm_rounds 20 --model clip --batch_size 256 --pub_data_num 5000 --use_pretrained_proj 0 --partition hetero >outputs/output_md_siglip.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-df --FL_algorithm FedDF --data_root "$IMAGENET_SIGLIP_ROOT" --feature_dim 768 --lr 1e-5 --local_epochs 1 --comm_rounds 20 --model clip --batch_size 256 --pub_data_num 5000 --use_pretrained_proj 0 --partition hetero >outputs/output_df_siglip.log 2>&1 &

CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-Cream --FL_algorithm Cream --data_root "$IMAGENET_SIGLIP_ROOT" --feature_dim 768 --lr 1e-5 --local_epochs 1 --comm_rounds 20 --model clip --batch_size 256 --pub_data_num 5000 --use_pretrained_proj 0 --partition hetero >outputs/output_cream_siglip.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-Harmony --FL_algorithm Harmony --data_root "$IMAGENET_SIGLIP_ROOT" --feature_dim 768 --lr 1e-5 --local_epochs 1 --comm_rounds 20 --model clip --batch_size 256 --use_pretrained_proj 0 --partition hetero >outputs/output_Harmony_siglip.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-MASA --FL_algorithm MASA --data_root "$IMAGENET_SIGLIP_ROOT" --feature_dim 768 --lr 1e-5 --local_epochs 1 --comm_rounds 20 --model clip --batch_size 256 --use_pretrained_proj 0 --partition hetero >outputs/output_MASA_siglip.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-MEMA --FL_algorithm FedMEMA --data_root "$IMAGENET_SIGLIP_ROOT" --feature_dim 768 --lr 1e-5 --local_epochs 1 --comm_rounds 20 --model clip --batch_size 256 --use_pretrained_proj 0 --partition hetero >outputs/output_FedMEMA_siglip.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-mobile --FL_algorithm FedMobile --data_root "$IMAGENET_SIGLIP_ROOT" --feature_dim 768 --lr 1e-5 --local_epochs 1 --comm_rounds 20 --model clip --batch_size 256 --use_pretrained_proj 0 --partition hetero >outputs/output_FedMobile_siglip.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-MEKT --FL_algorithm FedMEKT --data_root "$IMAGENET_SIGLIP_ROOT" --feature_dim 768 --lr 1e-5 --local_epochs 1 --comm_rounds 20 --model clip --batch_size 256 --use_pretrained_proj 0 --partition hetero >outputs/output_FedMEKT_siglip.log 2>&1 &

CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP --FL_algorithm FedMMDP --data_root "$IMAGENET_SIGLIP_ROOT" --feature_dim 768 --lr 1e-5 --local_epochs 1 --comm_rounds 20 --model clip --batch_size 256 --use_pretrained_proj 0 --partition hetero >outputs/output_FedMMDP_siglip.log 2>&1 &
