export IMAGENET_SIGLIP_ROOT=/home/bd/data/zs/FedMMDP/preprocessed_imagenet/domain_datasets/siglip

USE_PRETRAINED_PROJ=${USE_PRETRAINED_PROJ:-0}
PROJ_TAG=$([ "$USE_PRETRAINED_PROJ" -eq 1 ] && echo preproj || echo randproj)


CUDA_VISIBLE_DEVICES=1 python src/main.py --name FedMMDP-avg-siglip --FL_algorithm FedAvg --data_root "$IMAGENET_SIGLIP_ROOT" --feature_dim 768 --lr 1e-5 --local_epochs 1 --comm_rounds 40  --batch_size 256 --model siglip --use_pretrained_proj "$USE_PRETRAINED_PROJ" --partition hetero >outputs/output_avg_siglip_${PROJ_TAG}.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 python src/main.py --name FedMMDP-prox-siglip --FL_algorithm FedProx --data_root "$IMAGENET_SIGLIP_ROOT" --feature_dim 768 --lr 1e-5 --local_epochs 1 --comm_rounds 40 --model siglip --batch_size 256 --use_pretrained_proj "$USE_PRETRAINED_PROJ" --partition hetero >outputs/output_prox_siglip_${PROJ_TAG}.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 python src/main.py --name FedMMDP-md-siglip --FL_algorithm FedMD --data_root "$IMAGENET_SIGLIP_ROOT" --feature_dim 768 --lr 1e-5 --local_epochs 1 --comm_rounds 40 --model siglip --batch_size 256 --pub_data_num 5000 --use_pretrained_proj "$USE_PRETRAINED_PROJ" --partition hetero >outputs/output_md_siglip_${PROJ_TAG}.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 python src/main.py --name FedMMDP-df-siglip --FL_algorithm FedDF --data_root "$IMAGENET_SIGLIP_ROOT" --feature_dim 768 --lr 1e-5 --local_epochs 1 --comm_rounds 40 --model siglip --batch_size 256 --pub_data_num 5000 --use_pretrained_proj "$USE_PRETRAINED_PROJ" --partition hetero >outputs/output_df_siglip_${PROJ_TAG}.log 2>&1 &

CUDA_VISIBLE_DEVICES=2 python src/main.py --name FedMMDP-Cream-siglip --FL_algorithm Cream --data_root "$IMAGENET_SIGLIP_ROOT" --feature_dim 768 --lr 1e-5 --local_epochs 1 --comm_rounds 40 --model siglip --batch_size 256 --pub_data_num 5000 --use_pretrained_proj "$USE_PRETRAINED_PROJ" --partition hetero >outputs/output_cream_siglip_${PROJ_TAG}.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 python src/main.py --name FedMMDP-Harmony-siglip --FL_algorithm Harmony --data_root "$IMAGENET_SIGLIP_ROOT" --feature_dim 768 --lr 1e-5 --local_epochs 1 --comm_rounds 40 --harmony_stage1_rounds 10 --harmony_clusters 2 --harmony_cluster_mode fixed --model siglip --batch_size 256 --use_pretrained_proj "$USE_PRETRAINED_PROJ" --partition hetero >outputs/output_Harmony_siglip_${PROJ_TAG}.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 python src/main.py --name FedMMDP-MASA-siglip --FL_algorithm MASA --data_root "$IMAGENET_SIGLIP_ROOT" --feature_dim 768 --lr 1e-5 --local_epochs 1 --comm_rounds 40 --model siglip --batch_size 256 --use_pretrained_proj "$USE_PRETRAINED_PROJ" --partition hetero >outputs/output_MASA_siglip_${PROJ_TAG}.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 python src/main.py --name FedMMDP-MEMA-siglip --FL_algorithm FedMEMA --data_root "$IMAGENET_SIGLIP_ROOT" --feature_dim 768 --lr 1e-5 --local_epochs 1 --comm_rounds 40 --model siglip --batch_size 256 --use_pretrained_proj "$USE_PRETRAINED_PROJ" --partition hetero >outputs/output_FedMEMA_siglip_${PROJ_TAG}.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-mobile-siglip --FL_algorithm FedMobile --data_root "$IMAGENET_SIGLIP_ROOT" --feature_dim 768 --lr 1e-5 --local_epochs 1 --comm_rounds 40 --model siglip --batch_size 256 --use_pretrained_proj "$USE_PRETRAINED_PROJ" --partition hetero >outputs/output_FedMobile_siglip_${PROJ_TAG}.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-MEKT-siglip --FL_algorithm FedMEKT --data_root "$IMAGENET_SIGLIP_ROOT" --feature_dim 768 --lr 1e-5 --local_epochs 1 --comm_rounds 40 --model siglip --batch_size 256 --use_pretrained_proj "$USE_PRETRAINED_PROJ" --partition hetero >outputs/output_FedMEKT_siglip_${PROJ_TAG}.log 2>&1 &

CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-siglip --FL_algorithm FedMMDP --data_root "$IMAGENET_SIGLIP_ROOT" --feature_dim 768 --lr 1e-5 --local_epochs 1 --comm_rounds 40 --model siglip --batch_size 256 --use_pretrained_proj "$USE_PRETRAINED_PROJ" --partition hetero >outputs/output_FedMMDP_siglip_${PROJ_TAG}.log 2>&1 &
