export IAPR_CLIP_ROOT=/home/bd/data/zs/FedMMDP/preprocessed_iapr/domain_datasets

CUDA_VISIBLE_DEVICES=1 python src/main.py --name FedMMDP-avg --FL_algorithm FedAvg --dataset iapr --data_root "$IAPR_CLIP_ROOT" --lr 1e-5 --local_epochs 1 --comm_rounds 20  --batch_size 256 --model clip --use_pretrained_proj 0 --partition hetero >outputs/output_avg_clip_iapr.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 python src/main.py --name FedMMDP-prox --FL_algorithm FedProx --dataset iapr --data_root "$IAPR_CLIP_ROOT" --lr 1e-5 --local_epochs 1 --comm_rounds 20 --model clip --batch_size 256 --use_pretrained_proj 0 --partition hetero >outputs/output_prox_iapr.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 python src/main.py --name FedMMDP-md --FL_algorithm FedMD --dataset iapr --data_root "$IAPR_CLIP_ROOT" --lr 1e-5 --local_epochs 1 --comm_rounds 20 --model clip --batch_size 256 --pub_data_num 5000 --use_pretrained_proj 0 --partition hetero >outputs/output_md_iapr.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 python src/main.py --name FedMMDP-df --FL_algorithm FedDF --dataset iapr --data_root "$IAPR_CLIP_ROOT" --lr 1e-5 --local_epochs 1 --comm_rounds 20 --model clip --batch_size 256 --pub_data_num 5000 --use_pretrained_proj 0 --partition hetero >outputs/output_df_iapr.log 2>&1 &

CUDA_VISIBLE_DEVICES=2 python src/main.py --name FedMMDP-Cream --FL_algorithm Cream --dataset iapr --data_root "$IAPR_CLIP_ROOT" --lr 1e-5 --local_epochs 1 --comm_rounds 20 --model clip --batch_size 256 --pub_data_num 5000 --use_pretrained_proj 0 --partition hetero >outputs/output_cream_iapr.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 python src/main.py --name FedMMDP-Harmony --FL_algorithm Harmony --dataset iapr --data_root "$IAPR_CLIP_ROOT" --lr 1e-5 --local_epochs 1 --comm_rounds 20 --model clip --batch_size 256 --use_pretrained_proj 0 --partition hetero >outputs/output_Harmony_iapr.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-MASA --FL_algorithm MASA --dataset iapr --data_root "$IAPR_CLIP_ROOT" --lr 1e-5 --local_epochs 1 --comm_rounds 20 --model clip --batch_size 256 --use_pretrained_proj 0 --partition hetero >outputs/output_MASA_iapr.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-MEMA --FL_algorithm FedMEMA --dataset iapr --data_root "$IAPR_CLIP_ROOT" --lr 1e-5 --local_epochs 1 --comm_rounds 20 --model clip --batch_size 256 --use_pretrained_proj 0 --partition hetero >outputs/output_FedMEMA_iapr.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-Mobile --FL_algorithm FedMobile --dataset iapr --data_root "$IAPR_CLIP_ROOT" --lr 1e-5 --local_epochs 1 --comm_rounds 20 --model clip --batch_size 256 --use_pretrained_proj 0 --partition hetero >outputs/output_FedMobile_iapr.log 2>&1 &
CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-MEKT --FL_algorithm FedMEKT --dataset iapr --data_root "$IAPR_CLIP_ROOT" --lr 1e-5 --local_epochs 1 --comm_rounds 20 --model clip --batch_size 256 --use_pretrained_proj 0 --partition hetero >outputs/output_FedMEKT_iapr.log 2>&1 &

CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP --FL_algorithm FedMMDP --dataset iapr --data_root "$IAPR_CLIP_ROOT" --lr 1e-5 --local_epochs 1 --comm_rounds 20 --model clip --batch_size 256 --use_pretrained_proj 0 --partition hetero >outputs/output_FedMMDP_iapr.log 2>&1 &
