USE_PRETRAINED_PROJ=${USE_PRETRAINED_PROJ:-0}
PROJ_TAG=$([ "$USE_PRETRAINED_PROJ" -eq 1 ] && echo preproj || echo randproj)

CUDA_VISIBLE_DEVICES=1 python src/main.py --name FedMMDP-avg --FL_algorithm FedAvg --dataset imagenet --data_root /home/bd/data/zs/FedMMDP/preprocessed_imagenet/domain_datasets --lr 1e-5 --local_epochs 1 --comm_rounds 50  --batch_size 256 --model clip --use_pretrained_proj "$USE_PRETRAINED_PROJ" --partition hetero >outputs/output_avg_clip_${PROJ_TAG}.log 2>&1 &
# CUDA_VISIBLE_DEVICES=1 python src/main.py --name FedMMDP-prox --FL_algorithm FedProx --dataset imagenet --data_root /home/bd/data/zs/FedMMDP/preprocessed_imagenet/domain_datasets --lr 1e-5 --local_epochs 1 --comm_rounds 50 --model clip --batch_size 256 --use_pretrained_proj "$USE_PRETRAINED_PROJ" --partition hetero >outputs/output_prox_${PROJ_TAG}.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 python src/main.py --name FedMMDP-md --FL_algorithm FedMD --dataset imagenet --data_root /home/bd/data/zs/FedMMDP/preprocessed_imagenet/domain_datasets --lr 1e-5 --local_epochs 1 --comm_rounds 50 --model clip --batch_size 256 --pub_data_num 5000 --use_pretrained_proj "$USE_PRETRAINED_PROJ" --partition hetero >outputs/output_md_${PROJ_TAG}.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 python src/main.py --name FedMMDP-df --FL_algorithm FedDF --dataset imagenet --data_root /home/bd/data/zs/FedMMDP/preprocessed_imagenet/domain_datasets --lr 1e-5 --local_epochs 1 --comm_rounds 50 --model clip --batch_size 256 --pub_data_num 5000 --use_pretrained_proj "$USE_PRETRAINED_PROJ" --partition hetero >outputs/output_df_${PROJ_TAG}.log 2>&1 &

# CUDA_VISIBLE_DEVICES=2 python src/main.py --name FedMMDP-Cream --FL_algorithm Cream --dataset imagenet --data_root /home/bd/data/zs/FedMMDP/preprocessed_imagenet/domain_datasets --lr 1e-5 --local_epochs 1 --comm_rounds 50 --model clip --batch_size 256 --pub_data_num 5000 --use_pretrained_proj "$USE_PRETRAINED_PROJ" --partition hetero >outputs/output_cream_${PROJ_TAG}.log 2>&1 &
CUDA_VISIBLE_DEVICES=2 python src/main.py --name FedMMDP-Harmony --FL_algorithm Harmony --dataset imagenet --data_root /home/bd/data/zs/FedMMDP/preprocessed_imagenet/domain_datasets --lr 1e-5 --local_epochs 1 --comm_rounds 50 --harmony_stage1_rounds 10 --harmony_clusters 2 --harmony_cluster_mode fixed --model clip --batch_size 256 --use_pretrained_proj "$USE_PRETRAINED_PROJ" --partition hetero >outputs/output_Harmony_${PROJ_TAG}.log 2>&1 &
# CUDA_VISIBLE_DEVICES=2 python src/main.py --name FedMMDP-MASA --FL_algorithm MASA --dataset imagenet --data_root /home/bd/data/zs/FedMMDP/preprocessed_imagenet/domain_datasets --lr 1e-5 --local_epochs 1 --comm_rounds 50 --model clip --batch_size 256 --use_pretrained_proj "$USE_PRETRAINED_PROJ" --partition hetero >outputs/output_MASA_${PROJ_TAG}.log 2>&1 &
# CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-MEMA --FL_algorithm FedMEMA --dataset imagenet --data_root /home/bd/data/zs/FedMMDP/preprocessed_imagenet/domain_datasets --lr 1e-5 --local_epochs 1 --comm_rounds 50 --model clip --batch_size 256 --use_pretrained_proj "$USE_PRETRAINED_PROJ" --partition hetero >outputs/output_FedMEMA_${PROJ_TAG}.log 2>&1 &
# CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-Mobile --FL_algorithm FedMobile --dataset imagenet --data_root /home/bd/data/zs/FedMMDP/preprocessed_imagenet/domain_datasets --lr 1e-5 --local_epochs 1 --comm_rounds 50 --model clip --batch_size 256 --use_pretrained_proj "$USE_PRETRAINED_PROJ" --partition hetero >outputs/output_FedMobile_${PROJ_TAG}.log 2>&1 &
# CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-MEKT --FL_algorithm FedMEKT --dataset imagenet --data_root /home/bd/data/zs/FedMMDP/preprocessed_imagenet/domain_datasets --lr 1e-5 --local_epochs 1 --comm_rounds 50 --model clip --batch_size 256 --use_pretrained_proj "$USE_PRETRAINED_PROJ" --partition hetero >outputs/output_FedMEKT_${PROJ_TAG}.log 2>&1 &

# CUDA_VISIBLE_DEVICES=3 python src/main.py --name FedMMDP-MMDP --FL_algorithm FedMMDP --dataset imagenet --data_root /home/bd/data/zs/FedMMDP/preprocessed_imagenet/domain_datasets --lr 1e-5 --local_epochs 1 --comm_rounds 50 --model clip --batch_size 256 --use_pretrained_proj "$USE_PRETRAINED_PROJ" --partition hetero >outputs/output_FedMMDP_${PROJ_TAG}.log 2>&1 &
